### ISSUE TITLE
Free Flora doesnt have the correct uncensor art

### ISSUE THREAD

**Issue by mweggen** [Live2D-DCG/Live2D-DCG.github.io#1]

**Comment by Live2D-DCG** [comment]
I checked the Kr version and compared it with the Live2D model, I wasn't able to spot the differences. Can you provide me an image on what is different between the two?

**Comment by mweggen** [comment]
https://i.imgur.com/q9SvsNJ.jpg this is the one i got from bit.ly/DCUncensor

**Comment by Live2D-DCG** [comment]
The Korean version must've re-censored her due to her child-like appearance. I'm going to stick with what is currently shown in the Korean / JP  version.
