### ISSUE TITLE
I broke the downloader

### ISSUE THREAD

**Issue by ghost** [Live2D-DCG/Live2D-DCG.github.io#3]
Idk what happend, but i was messing around with the downloader at [https://live2d-dcg.github.io/gifChild.html](https://live2d-dcg.github.io/gifChild.html) and it stopped creating / downloading the zip files of those buttons
![image](https://user-images.githubusercontent.com/93844225/180229793-4c200885-1b59-464b-bfe2-dfb26204ae68.png)
The normal save image button which only saves the current frame still works.
Idk if i broke  something on your server or idk, but it doesnt work in any of my browsers anymore, not even on my mobile phone.

**Comment by ghost** [comment]
Seems to not even work with the downloaded npm version, it finishes the action but then doesnt save anything, just goes back to play the idle animation.
Meanwhile i got it to do it on my phone after some time passed (it was open) it randomly began downloading.

**Comment by Live2D-DCG** [comment]
Hi,

Not sure what happened. I didn't make any changes to the gif generator.
I was able to successfully click get FULL attack motion PNGs, etc.

Other people were able to create gifs from the website within the last 2
days, for example, https://gfycat.com/niftysecondkakapo

If you have discord try to contact me there "ToxicWayz#3274" as I don't
really check this email account much.
DCI - https://discord.gg/c4w4WkeF
DCG - https://discord.gg/tW3Spdz
